{
 "title": "Mosquitto",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mosquitto_total_clients", "legendFormat": "total" },
    { "expr": "mosquitto_expired_clients", "legendFormat": "expired" },
    { "expr": "mosquitto_connected_clients", "legendFormat": "connected" },
    { "expr": "mosquitto_disconnected_clients", "legendFormat": "disconnected" }
   ]
  },
  {
   "title": "Active subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mosquitto_active_subscriptions", "legendFormat": "subscriptions" }
   ]
  },
  {
   "title": "Received messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(mosquitto_received_messages_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(mosquitto_sent_messages_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(mosquitto_received_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(mosquitto_sent_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stored messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "mosquitto_stored_messages", "legendFormat": "messages" }
   ]
  },
  {
   "title": "Stored bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "mosquitto_stored_bytes", "legendFormat": "bytes" }
   ]
  },
  {
   "title": "Retained messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "mosquitto_retained_messages", "legendFormat": "messages" }
   ]
  }
 ]
}